disabled_rules: # rule identifiers to exclude from running
  - weak_delegate
  - class_delegate_protocol
opt_in_rules: # some rules are only opt-in
  - array_init
  - attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_first_not_nil
  - convenience_type
  - discouraged_optional_boolean
  - empty_count
  - empty_string
  - empty_xctest_method
  - explicit_init
  - fatal_error_message
  - first_where
  - for_where
  - implicit_return
  - is_disjoint
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - modifier_order
  - multiline_arguments
  - multiline_function_chains
  - multiline_parameters
  - nimble_operator
  - operator_usage_whitespace
  - operator_whitespace
  - overridden_super_call
  - override_in_extension
  - pattern_matching_keywords
  - private_action
  - private_unit_test
  - prohibited_super_call
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - redundant_discardable_let
  - redundant_nil_coalescing
  - single_test_class
  - sorted_first_last
  - sorted_imports
  - vertical_parameter_alignment_on_call
excluded:
  - Carthage
  - Pods
identifier_name:
  min_length: # only min_length
    error: 4 # only error
  excluded: # excluded via string array
    - id
    - app
    - url
    - tag
    - age
    - row
    - key
    - nib
    - min
    - gpa
    - max
    - sku
    - pin
    - tax
    - upc
    - lhs
    - rhs
    - ytd
    - mtd
    - uid
    - get
    - put
    - add
    - up
    - hex
    - lat
    - long
    - xts
    - ats
cyclomatic_complexity:
  ignores_case_statements: true
large_tuple:
  warning: 4
  error: 5
trailing_whitespace:
  ignores_empty_lines: true
  ignores_comments: true
nesting:
    type_level: 2
type_body_length:
  - 300 # warning
  - 400 # error
file_length:
  warning: 600
  error: 1200
  ignore_comment_only_lines: true
line_length:
  ignores_comments: true
  ignores_function_declarations: true
  ignores_interpolated_strings: true
  ignores_urls: true
